Repository prgrms-web-devcourse-final-project/WEB2_3_pawEver_FE, pull requests merged in 2025-02, with the labels that each got.

#13 💄 Design/CommonComponents
  index.html
  src/Router.tsx
  src/assets/icons/arrow.svg
  src/assets/icons/logo.svg
  src/common/ButtonComponent.tsx
  src/common/DropDownComponent.tsx
  src/common/InputComponent.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/RootLayout.tsx
  src/components/layout/SidebarM.tsx
  tailwind.config.js
Labels: Design

#18 💄 Design/Header_Footer_Fix
  src/Router.tsx
  src/common/ButtonComponent.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/SidebarM.tsx
  src/pages/Donation/Donation.tsx
Labels: 💄 Style

#26 [design/11-featurehome-publishing]💄 Style : home 퍼블리싱
  src/assets/images/example.png
  src/assets/images/main_img.png
  src/pages/Home/Home.tsx
Labels: 💄 Style

#41 [design/feature #35]💄 Style : AnimalBoard 퍼블리싱
  src/assets/icons/board-sliders.svg
  src/pages/AnimalBoard/AnimalBoard.tsx
  src/pages/Home/Home.tsx
Labels: 💄 Style

#47 [design/45-designdonation-page] :lipstick: design: donation-page publishing
  src/assets/images/paw.json
  src/common/InputComponent.tsx
  src/pages/Donation/Donation.tsx
  src/pages/Donation/components/DonationModal.tsx
Labels: 💄 Style

#49 [style/feature #42] 💄 style: 마이페이지 퍼블리싱
  src/assets/icons/edit.svg
  src/pages/UserPage/UserPage.tsx
Labels: 💄 Style

#50 [style/feature #42]✨ feat: 카카오맵 api
  src/components/KakaoMap.tsx
Labels: ✨Feature
