Repository prgrms-web-devcourse-final-project/WEB2_3_pawEver_FE, pull requests merged in 2025-03, with the labels that each got.

#56 [design/user/staff-page] :lipstick:user/staff-page 퍼블리싱
  src/Router.tsx
  src/assets/icons/cancel.svg
  src/assets/icons/edit.svg
  src/assets/icons/staffmark.svg
  src/assets/images/useritem_img.svg
  src/components/user/DonationModal.tsx
  src/components/user/ReservationModal.tsx
  src/components/user/UserDonation.tsx
  src/components/user/UserProfile.tsx
  src/components/user/UserReservation.tsx
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/components/UserMenu.tsx
  src/pages/UserPage/components/UserPost.tsx
  src/pages/staffpage/StaffPage.tsx
  src/pages/staffpage/components/StaffMenu.tsx
Labels: 💄 Style

#71 ReservationCalendar/MapMarker
  package.json
  pnpm-lock.yaml
  src/assets/icons/planner.svg
  src/pages/editreservation/EditReservation.tsx
Labels: ✨Feature

#72 [feature/comment]:sparkles: Feature: 게시글 검색, 댓글 기능 구현
  src/api/fetchComment.ts
  src/api/fetchCommunity.ts
  src/pages/community/Community.tsx
  src/pages/community/components/CommunityCard.tsx
  src/pages/communitydetail/CommunityDetail.tsx
  src/pages/communitydetail/components/Comment.tsx
  src/pages/communitydetail/components/CommentSection.tsx
  src/pages/editcommunity/EditCommunity.tsx
  src/types/Post.d.ts
Labels: ✨Feature

#79 [feat/matching-page]✨ feature: 매칭 페이지 log정리
  src/api/matchingAnimal.ts
  src/pages/matching/MatchingProgress.tsx
  src/pages/matching/MatchingResult.tsx
  src/pages/matching/components/MatchingCard.tsx
  src/pages/matching/components/MatchingOption.tsx
Labels: ✨Feature

#82 Design/sidebarIcons
  src/assets/icons/charity.svg
  src/assets/icons/community.svg
  src/assets/icons/reservation.svg
  src/components/layout/SidebarM.tsx
  src/pages/editreservation/EditReservation.tsx
Labels: 💄 Style

#83 :rotating_light: Fix: ui수정 및 기능 보완
  src/App.tsx
  src/assets/icons/comment.svg
  src/assets/icons/noSearchResult.svg
  src/assets/images/catimg1.jpg
  src/assets/images/catimg2.jpg
  src/assets/images/defaultThumbnail.svg
  src/assets/images/dogimg1.jpg
  src/assets/images/dogimg2.jpg
  src/assets/images/loadingPaw.json
  src/common/LoadingSpinner.tsx
  src/pages/community/Community.tsx
  src/pages/community/components/CommunityCard.tsx
  src/pages/communitydetail/CommunityDetail.tsx
  src/pages/communitydetail/components/Comment.tsx
  src/pages/communitydetail/components/CommentSection.tsx
  src/pages/editcommunity/EditCommunity.tsx
  src/pages/home/Home.tsx
  src/pages/home/components/DonationSection.tsx
  src/pages/home/components/FilterSection.tsx
  src/types/Comment.d.ts
  src/types/Post.d.ts
  src/utils/formatDate.ts
  src/utils/getRelativeTime.ts
Labels: 🚨Fix
